name: Integration Tests with HiveMQ

on:
  push:
    branches:
      - feat/TestContainers
  pull_request:
    branches:
      - feat/TestContainers

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      hivemq:
        image: hivemq/hivemq-ce:latest
        ports:
          - 1883:1883  # Exposing the MQTT port
        options: --health-cmd "nc -zv 127.0.0.1 1883" --health-timeout 30s --health-retries 3  # Health check to ensure HiveMQ is ready

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker
        run: docker pull hivemq/hivemq-ce:latest
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      - name: Install Maven
        run: sudo apt-get install maven

      - name: Run tests
        run: mvn clean test  # Running the tests
